import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import MouseTrail from "./components/MouseTrail";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "Info tac",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-7xl mx-auto antialiased h-screen`}
      >
        <MouseTrail />
        <Navbar />
         <div className="h-screen">
           {children}
         </div>
        <Footer/>
      </body>
    </html>
  );
}
